# Generated by Django 3.2.8 on 2021-10-09 18:45

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('phoneDetection', '0002_rename_statusoftrip_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='offence',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
