# Generated by Django 3.2.8 on 2021-10-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneDetection', '0003_auto_20211010_0245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='date',
            field=models.DateTimeField(),
        ),
    ]
