# Generated by Django 3.2.8 on 2021-10-10 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phoneDetection', '0004_alter_trip_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trip',
            old_name='date',
            new_name='dateEnd',
        ),
        migrations.AddField(
            model_name='driver',
            name='location',
            field=models.CharField(default='Singapore', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='driver',
            name='phone',
            field=models.CharField(default=98312831, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip',
            name='dateStart',
            field=models.DateTimeField(default='2021-10-10 17:21:21'),
            preserve_default=False,
        ),
    ]
