# Generated by Django 3.2.8 on 2021-10-10 13:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('phoneDetection', '0005_auto_20211010_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name='offence',
            name='trip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='phoneDetection.trip'),
        ),
    ]
