# Generated by Django 3.2.8 on 2021-10-10 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('phoneDetection', '0006_auto_20211010_2119'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offence',
            name='trip',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='phoneDetection.trip'),
        ),
    ]
